### ISSUE TITLE
any ETA on release v0.0.2?

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/actions#107]
Hey @glenn-jocher, the latest release of this action is from 5 months back. Do you have any ETA for the next release (v0.0.2)?

**Comment by glenn-jocher** [comment]
@fcakyon that's a good question! I've been running the actions with @main rather than on a release, but yes you are right I should issue a new release here soon.

```yaml
    steps:
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@main
```
