### ISSUE TITLE
Can we provide a custom spell list and ignore list?

### ISSUE THREAD

**Issue by kalenmike** [ultralytics/actions#62]
We don't want to run spellcheck on package file names, can we ignore package and requirement files? Also can we provide a custom word list for custom exceptions?

**Comment by glenn-jocher** [comment]
@kalenmike yes, I've been thinking the same thing. As the actions grow there are a few options here, but they each have their drawbacks:

### Single Repo - Single Branch (current approach, comingling arguments)

```yaml
jobs:
  ultralytics-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, do not modify
          actions-arg1:
          actions-arg2:
          ...
```

### Single Repo - Multi Branch (non-conventional, more complicated to maintain)

Here a single repo supports multiple branches that are named for their step, i.e. `format` branch and `summary` branches, etc.

```yaml
jobs:
  ultralytics-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@format
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, do not modify
          format-arg1:
          format-arg2:
          ...

      - name: Run Ultralytics Summary
        uses: ultralytics/actions@summary
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, do not modify
          summary-arg1:
          summary-arg2:
          ...
```

### Multi Repo (higher maintenance, duplication of effort, etc.)

Here a single repo supports a single step in it's `main` branch. The downside here is we would have to maintain multiple repos in parallel, multiplying maintenance and having to repeat actions across repos (like approving dependabot updates etc.)

```yaml
jobs:
  ultralytics-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions-format@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, do not modify
          format-arg1:
          format-arg2:
          ...

      - name: Run Ultralytics Summary
        uses: ultralytics/actions-summary@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, do not modify
          summary-arg1:
          summary-arg2:
          ...
```
